# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 313cd7464044fa8a1c652621c8803b059f99d8e939c66937776ec1874356575f60ae578f33d6f5dc44d39e4c280356a7bd0d4893513c9b684b0b16c8f19e3fd0

test:
  secret_key_base: c256fd3f1c06e94720678b56556eda3227b378c0da5444aded6691c0603c89be2a432983377faaed508e02c5767d84f16f3ff2963a1760903b5729e774cba4df

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
